import { PlanFormSchemaType } from "@/api/services/plan/types";
import { FormFieldConfig } from "@/components/FormRenderer/types";

// imageUrl: z.string(),

export const planFormFields: FormFieldConfig<PlanFormSchemaType>[] = [
  {
    label: "募資類別",
    name: "activeType",
    type: "radio",
    id: "activeType",
    placeholder: "請輸入募資類別",
    key: "activeType",
    options: [
      { label: "群眾募資", value: "A" },
      { label: "訂閱式專案", value: "B" },
    ],
    orientation: "horizontal",
  },
  {
    label: "餐廳地區",
    name: "location",
    type: "select",
    id: "location",
    placeholder: "請輸選擇您餐廳的地區",
    key: "location",
    options: [
      { label: "台北市", value: "台北市" },
      { label: "新北市", value: "新北市" },
    ],
  },
  {
    label: "募資標題",
    name: "title",
    type: "text",
    id: "title",
    placeholder: "請輸入您的募資標題",
    key: "title",
  },
  {
    label: "募資封面",
    name: "image",
    type: "file",
    id: "image",
    placeholder: "請輸入您的募資封面",
    key: "image",
    enableCrop: true,
  },
  {
    label: "餐廳類別",
    name: "restaurantType",
    type: "radio",
    id: "restaurantType",
    placeholder: "請選擇您的餐廳類別",
    key: "restaurantType",
    options: [
      { label: "中式料理", value: "中式料理" },
      { label: "日式料理", value: "日式料理" },
      { label: "義式料理", value: "義式料理" },
      { label: "泰式料理", value: "泰式料理" },
      { label: "美式料理", value: "美式料理" },
      { label: "歐式料理", value: "歐式料理" },
    ],
    orientation: "horizontal",
  },
  {
    label: "餐廳地址",
    name: "address",
    type: "text",
    id: "address",
    placeholder: "請輸入您的餐廳地址",
    key: "address",
  },
  {
    label: "提案人姓名",
    name: "proposer",
    type: "text",
    id: "proposer",
    placeholder: "請輸入您的提案人姓名",
    key: "proposer",
  },
  {
    label: "信箱",
    name: "email",
    type: "email",
    id: "email",
    placeholder: "請輸入您的電子郵件",
    key: "email",
  },
  {
    label: "聯絡電話",
    name: "phone",
    type: "text",
    placeholder: "請輸入您的聯絡電話",
    id: "phone",
    key: "phone",
  },
  {
    label: "提案敘述",
    name: "info",
    type: "textarea",
    id: "info",
    placeholder: "請輸入您的提案敘述",
    key: "info",
  },
  {
    label: "起始時間",
    name: "activeTime",
    type: "date",
    id: "activeTime",
    placeholder: "請再次輸入您的起始時間",
    key: "activeTime",
  },
  {
    label: "結束時間",
    name: "endAt",
    type: "date",
    id: "endAt",
    placeholder: "請輸入您的結束時間",
    key: "endAt",
  },
  {
    label: "目標金額",
    name: "targetAmount",
    type: "tel",
    id: "targetAmount",
    placeholder: "請輸入您的目標金額",
    key: "targetAmount",
  },
];
